# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHarveyNorman():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_harveyNorman(self):
    self.driver.get("https://www.harveynorman.com.my/apple/")
    self.driver.set_window_size(1057, 800)
    self.driver.find_element(By.ID, "attraqt_search").click()
    self.driver.find_element(By.ID, "attraqt_search").send_keys("iPhone 13")
    self.driver.find_element(By.ID, "attraqt_search").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-search")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.LINK_TEXT, "3")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "facet-product_type_iPhones").click()
    self.driver.execute_script("window.scrollTo(0,128.8000030517578)")
    self.driver.find_element(By.ID, "sw_elm_sort_fields").click()
    self.driver.find_element(By.LINK_TEXT, "Sort by Price: Low to High").click()
    self.driver.find_element(By.LINK_TEXT, "Apple iPhone 13 128GB - Midnight (MLPF3ZP/A)").click()
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.execute_script("window.scrollTo(0,400)")
    element = self.driver.find_element(By.ID, "button_cart_75164")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "button_cart_75164").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "det_img_75164642c3c01c1946_71197")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,200)")
  
