# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestShopee():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_shopee(self):
    self.driver.get("https://shopee.com.my/machines_os#product_list")
    self.driver.set_window_size(1053, 799)
    self.driver.execute_script("window.scrollTo(0,5310.39990234375)")
    self.driver.find_element(By.CSS_SELECTOR, ".shopee-searchbar-input__input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".shopee-searchbar-input__input").send_keys("iPhone 13")
    self.driver.find_element(By.CSS_SELECTOR, ".shopee-searchbar-input__input").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-xs-2-4:nth-child(3) .VTjd7p")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".select-with-status__holder").click()
    self.driver.find_element(By.CSS_SELECTOR, ".select-with-status__dropdown-item:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-xs-2-4:nth-child(3) .VTjd7p").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,300)")
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(1) > .flex > .product-variation:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn--l > span").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
  
